### ISSUE TITLE
How to obtain the token?

### ISSUE THREAD

**Issue by S4nderr** [AustynKoky/TicketScoop#2]
Hello,

I'm new to all of this. Could you please guide me on obtaining the token?

**Comment by kenjibailly** [comment]
I would love to know as well!

**Comment by KokyCode** [comment]
Hi all. In order to get your AUTH token you will need use a HTTPS scraper such as Fiddler or proxyman and connect it to your phone. Once connected, open the ticketswap app and do any request such as add to cart, you can then scrape the AUTH token. It's been a while since I've worked on this so unsure if it still works. @kenjibailly @S4nderr

**Comment by Roby09** [comment]
`Traceback (most recent call last):
  File "/Users/user/Desktop/TS/TicketScoop-main/scooper.py", line 179, in <module>
    getEventIdBrowser(eventLink)
  File "/Users/user/Desktop/TS/TicketScoop-main/scooper.py", line 47, in getEventIdBrowser
    getEventLinkInfoMobile(eventId)
  File "/Users/user/Desktop/TS/TicketScoop-main/scooper.py", line 87, in getEventLinkInfoMobile
    availabletickets = jsonresp['data']['node']['availableTicketsCount']
KeyError: 'data'` - Getting this error after the script responds 'failed to find ticket'. How do I fix this?
