### ISSUE TITLE
Error with correct AUTH token

### ISSUE THREAD

**Issue by hardtim3r** [AustynKoky/TicketScoop#3]
Hi! I should have the right AUTH key set up, but I'm still getting this error:

Traceback (most recent call last):
  File "c:\Users\jobni\OneDrive\Desktop\Test\TicketScoop-main\scooper.py", line 179, in <module>
    getEventIdBrowser(eventLink)
  File "c:\Users\jobni\OneDrive\Desktop\Test\TicketScoop-main\scooper.py", line 47, in getEventIdBrowser
    getEventLinkInfoMobile(eventId)
  File "c:\Users\jobni\OneDrive\Desktop\Test\TicketScoop-main\scooper.py", line 87, in getEventLinkInfoMobile
    availabletickets = jsonresp['data']['node']['availableTicketsCount']
                       ~~~~~~~~^^^^^^^^
KeyError: 'data'

What would be the issue? Help would be greatly appreciated.

Thank you in advance :)

**Comment by hardtim3r** [comment]
Okay so I was using ticketswap.nl, I've now switched to ticketswap.com and I get the following error:

 File "c:\Users\jobni\OneDrive\Desktop\Test\TicketScoop-main\scooper.py", line 179, in <module>
    getEventIdBrowser(eventLink)
  File "c:\Users\jobni\OneDrive\Desktop\Test\TicketScoop-main\scooper.py", line 43, in getEventIdBrowser
    res = x.find(id="__NEXT_DATA__").string
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'string'
